source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'

target 'lostfilm' do
  pod 'CarbonKit'
  pod 'SDWebImage', :modular_headers => true
  pod 'hpple', :git => 'https://github.com/topfunky/hpple.git'
  pod 'DVAppCore', :git => 'https://github.com/denis-vashkovski/DVAppCore.git'
  pod 'DVHtmlToModels', :git => 'https://github.com/denis-vashkovski/DVHtmlToModels.git'

  target 'lostfilmTests' do
    inherit! :search_paths
  end
end
