source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'

target 'lostfilm' do
  pod 'CarbonKit'
  pod 'SDWebImage', :modular_headers => true
  pod 'hpple', :git => 'https://github.com/topfunky/hpple.git'
  pod 'DVAppCore', :git => 'https://github.com/michail-lazarau/DVAppCore.git'
  pod 'DVHtmlToModels', :git => 'https://github.com/denis-vashkovski/DVHtmlToModels.git'
  pod 'SwiftLint'

  target 'lostfilmTests' do
    inherit! :search_paths
  end
end
